### ISSUE TITLE
Dropped Connections

### ISSUE THREAD

**Issue by MattComb** [deniszykov/WebSocketListener#1]
Hi Denis, firstly thanks to you and Val for this code base, it is very useful.

I have a few issues with Ping. I have built a WebSocket server loosely based on the RxChatroom app except I have decoupled the "chat" sub protocol and have a connection auto join based on a query parameter attained on connect.

I am suffering disconnects on the connections, however, and it appears to be ping related. Here is some information.

1. In Val's code, I commented out the TryPing and it was working. I am unsure what the flow on effect of doing this is.
2. I moved to your code base but I am unsure the correct way to disable ping functionality (if that should be done)
3. I have tried all ping modes but experience the same behaviour
4. I have also tried setting the ping latency timeout to infinite (as mentioned below) but this does not have any effect either.
5. In the observer OnNext method, I am treating each msgIn as a message (as I don't support join any more). and therefore am creating a messagehandler each time. I am noticing however that this is being triggered even on a connect that sends nothing and I'm unsure where the entry point is for that so that I can suppress it.

I have seen in Val's issue here:

https://github.com/vtortola/WebSocketListener/issues/106

For this person setting ping to infinite resolved the issue, but this does not work for me with your fork.

Do you have any suggestions?

Regards,

Matt.

**Comment by MattComb** [comment]
I'm not convinced this is Ping related

I reverted my service back to use Val's code base and it started working correctly again. With Val's code I do have StartPing commented out, however, with Denis' version, I did not seem to be triggering ping methods. Here are some peculiarities on the version based on Denis repo:

1. Two connections can connect and maintain using PingMode manual
2. If they join different chat rooms they can send messages freely
3. If they join the same chatroom the <b>receiver</b> (connection not sending the message) will disconnect

Startup code looks like this:

                //var cancellation = new CancellationTokenSource();

                //var endpoint = new IPEndPoint(IPAddress.Any, 8001);
                //var options = new WebSocketListenerOptions() { SubProtocols = new[] { "chat" } };
                //options.PingMode = PingMode.Manual;
                //options.PingTimeout = Timeout.InfiniteTimeSpan;

                //options.Standards.RegisterRfc6455(rfc6455 =>
                //{
                //    rfc6455.MessageExtensions.RegisterDeflateCompression();
                //});
                //X509Certificate2 cert = new X509Certificate2(@"c:\development\abc.pfx", "xyz");
                //options.ConnectionExtensions.RegisterSecureConnection(cert);

                //var Server = new WebSocketListener(endpoint, options);


                ////.ConnectionExtensions

                //Server.StartAsync().Wait();
                ////Log("Rx Chat Server started at " + endpoint.ToString());

                //var chatRoomManager = new ChatRoomManager();
                //var chatSessionObserver = new ChatSessionsObserver(chatRoomManager);

                //Observable.FromAsync(Server.AcceptWebSocketAsync)
                //    .Select(ws => new ChatSession(ws, chatRoomManager)
                //    {
                //        In = Observable.FromAsync<dynamic>(ws.ReadDynamicAsync)
                //            .DoWhile(() => ws.IsConnected)
                //            .Where(msg => msg != null),

                //        Out = Observer.Create<dynamic>(ws.WriteDynamic)
                //    })
                //    .DoWhile(() => Server.IsStarted && !cancellation.IsCancellationRequested)
                //    .Subscribe(chatSessionObserver);

**Comment by deniszykov** [comment]
Hi Matt!
2) To disable Ping functionality you need to set PingMode = PingMode.Manual (and call WebSocket.PingAsync if u need to ping
5) I'm not very familiar with this Rx and can't understand control flow of your code. 

As Val described in [issue#106](https://github.com/vtortola/WebSocketListener/issues/106) you need constantly receive messages for the normal functioning of WS. You should read message, dispose message stream and then queue incoming messages in constant loop untill null message is received (null message = connection close). Here is example code: [EchoServer](https://github.com/deniszykov/WebSocketListener/blob/master/Samples/EchoServer/Program.cs)

```
while (webSocket.IsConnected && !cancellation.IsCancellationRequested)
{
    var messageText = await webSocket.ReadStringAsync(cancellation).ConfigureAwait(false);
    if (messageText == null)
         break; // webSocket is disconnected
    queue.Enqueue(messageText);
}
```

Also, worth mentioning. Mono on windows randomly crashes when using sockets under load. Mono on linux is randomly shutting down sockets under load. This is reported bugs and they are not fixed in years.

**Comment by deniszykov** [comment]
HI @MattComb i found bug related to ```PingMode.BandwidthSaving``` and fixed it in d1db1447b7171a61815da61d86406c33216300bc
This could fix your disconnection problem.

**Comment by BrandonLWhite** [comment]
FYI.  No plan to change, just good to know it's been taken care of.

--
Best regards,

Brandon White|Software Engineer| C: 713-294-8981 
|brandonlwhite@gmail.com




------ Original Message ------

**Comment by MattComb** [comment]
Hi Denis,

Thanks very much for letting me know, I will attempt to test it over the next week or so and let you know the results.

Currently I had reverted back to Val's version and have a working solution, however, there were performance related improvements in your version which are desirable so I am keen to make the shift sooner rather than later.

Best Regards,

Matt.

**Comment by MattComb** [comment]
Hi Denis,

Sorry this has taken so long to get back to. Hard to believe its been a year, but things have been moving fast here.

Only recently am I converting from Val's version to yours and I can confirm that the fix you posted has resolved the issue I believe.
