### ISSUE TITLE
Parallel TakeAsync is not allowed

### ISSUE THREAD

**Issue by Lroca88** [deniszykov/WebSocketListener#11]
Hi,

I'm running the WebSocketListener server inside a windows service, the issue I'm presenting is that on user logon, the service will start the websocket server, but I get this error every time:
`Error Accepting clients: Parallel TakeAsync is not allowed`

On the other hand, If I restart the service it works well. My assumption is that has to be related with the user logon. Any ideas about this?

**Comment by deniszykov** [comment]
Hi, you probably u do AcceptWebSocketAsync in parallel, which is not allowed. You should wait untill AcceptWebSocketAsync is completed and only when retry call.

**Comment by Lroca88** [comment]
I think this is not the case. I have a pretty good logs file that describes when I'm calling AcceptWebSocketAsync(). It only happens once, when the user logs in the machine.

`2017-11-30 13:42:21,750 INFO  [MTA.ControllerStandardLibs.CommonLibs.WebSockets.WebSocketServer] Calling Server.AcceptWebSocketAsync`
`2017-11-30 13:42:21,750 ERROR [MTA.ControllerStandardLibs.CommonLibs.WebSockets.WebSocketServer] Error Accepting clients: Parallel TakeAsync is not allowed.`
`2017-11-30 13:42:29,488 INFO  [MTA.ControllerStandardLibs.CommonLibs.WebSockets.WebSocketServer] Client '[::1]:57769' connected.`

**The code works when I start the service manually** from my user's session, but not when it starts automatically on boot. To my point, if I'm calling AcceptWebSocketAsync in parallel would fail in both.

**Comment by deniszykov** [comment]
Could you provide code where AcceptWebSocketAsync is called.

**Comment by Lroca88** [comment]
This code is called once, with `AcceptWebSocketClientsAsync().Result;` I just want one client connected.
```
        public async Task<bool> AcceptWebSocketClientsAsync()
        {
            try
            {
                Logger.LogInformation("Calling Server.AcceptWebSocketAsync");
                var webSocket = await Server.AcceptWebSocketAsync(CancellationToken.Token).ConfigureAwait(false);
                if (webSocket != null) HandleConnectionAsync(webSocket, CancellationToken.Token);
                return webSocket != null && webSocket.IsConnected;
            }
            catch (Exception aex)
            {
                Logger.LogError($"Error Accepting clients: {aex.GetBaseException().Message}");
                return false;
            }
        }
```

**Comment by deniszykov** [comment]
Are you sure not reusing 'Server' across threads?

**Comment by Lroca88** [comment]
How can I send you the entire class?

**Comment by deniszykov** [comment]
Yes. You could use https://pastebin.com/ or https://gist.github.com/

**Comment by Lroca88** [comment]
I think the problem is in the line 117, but not 100% certain. Could you take a look please.
[The code is here](https://gist.github.com/lroca88/c2a9430138885945a5cee493b7cfd524)
In case this is the error, could you suggest me a solution on achieving the websocketserver to listen for only one client after that client drops the connection.

**Comment by deniszykov** [comment]
> ... earlier
> [Thread#1] Calling Server.AcceptWebSocketAsync
> ________________
> [Thread#2] Calling Server.AcceptWebSocketAsync
> [Thread#2] Error Accepting clients: Parallel TakeAsync is not allowed.
> [Thread#1] Client '[::1]:57769' connected.

According to logs there is 2 concurrent threads. One is accepting connection and second one is attempted to call AcceptWebSocketAsync and got error. How it happens ... i don't know, code is no-linear and it is hard to trace.

**Comment by Lroca88** [comment]
Thanks Denis,
I have located the issue, it turned to be the **line 117**, I wanted to get the websocketserver waiting on a single connection and whenever that single connection gets closed, I tried from the method `ReadMessage(...)` to put the websocketserver to listen again.

Well, it seems that's not how it works :). I'll have to find another way to implement the desired behavior.

**Comment by deniszykov** [comment]
Okay. Anyway I have added better error message for this case in 5fb79caeadf4987027a82ce798cf933421a8102b.
