### ISSUE TITLE
use of Task.Delay in mono app

### ISSUE THREAD

**Issue by warenbe** [deniszykov/WebSocketListener#14]
Hello,

i have a question: i'm using the websocketlistener in one of my app with sometime "lot" of clients connected. 
for example 200 client connected

i've designed the app like this: 

i'm runnin the AcceptWebsocketAsync method in a task.run statement. 
each time a client is connecting, i create an object with : 
- 1 loop created using a task.run to write the pending messages to the client
- 1 loop, waiting for the next message sent by the client.

I also have some other loop in the app, all are waiting with Task.Delay
On windows, no problems. but as soon as i run the same app on centos 7 using latest mono available, i have a very high CPU usage (and load average) as soon as i connect more that 5/10 clients...
i also see that the app is creating lot of threads and never release them. on Windows i don't see this problem.
so i suppose there is a problem with Task.Delay implementation in mono ??

My Question Is : 

is my design correct ? (the server create a new task for each client to read/write the messages)
should i create myself the thread for each clients and wait in the loop with Thread.sleep ?

i cannot share the code right now so if it need more explanation tells me

**Comment by deniszykov** [comment]
> so i suppose there is a problem with Task.Delay implementation in mono ??

I would not exclude this option. 
But why you need Task.Delay? Do you check for outgoing messages? Check connection status? 
Are you sure there is no pending locks(Monitor, EventHandler...)? Do you use message compression (it blocks threads while compressing/decompressing, fully async implementation require re-write of whole module)?

**Comment by warenbe** [comment]
Well, 
my app is running like this: 

Class library 1 is in charge of reading and writing in a TCP socket with a server. (2 threads are dedicated to this)



Each time this module read something, he send an event (1 different event per kind of message received) to the main module

Class library 2 is the websocket server.
the WS server is running and accepting clients. each time a client is accepted, the client is added to a concurrentdictionnary (string, websocketclient).

Class library 2 is the main library.

Each time the library 1 send an event to the main library (3),this one analyse the message and if needed, inform a class that a message should be sent to the websocket clients with an event.
(maybe i should just add the event to analyse to a concurrentqueue, than analyse it in another thread ? because the analyse is made directly in the thread of the library that sent the event right ?)

The main library then add the message to a concurrentqueue in each client connected to the server. and a loop in the client then send the waiting messages.

I have no more lock (only using concurrentbag/queue/dictionnary to avoid creating myself locks)
maybe i'm not understanding Task correctly : 
for me, these lines create a new thread and the execution is made out of the current thread, right ?

In library 2, when a new client is accepted, i'm creating an object "websocketclient" (not your class, mine class) and call this method: 
```

        public void Start()
        {
            Task taskWrite = new Task(() => WriteAsync(), TaskCreationOptions.LongRunning);
            taskWrite.Start();
            Task taskRead = new Task(() => ReadAsync(), TaskCreationOptions.LongRunning);
            taskRead.Start();
        }

        public async Task ReadAsync()
        {
            await Task.Yield();

            try
            {
                while (sock.IsConnected)
                {
                    string msgContent = await sock.ReadStringAsync(CancellationToken.None);
                    WebsocketMessage msg = null;
                    if (msgContent != null)
                    {
                        dateDernierMessageRecu = DateTime.Now;
                        msg = JsonConvert.DeserializeObject<WebsocketMessage>(msgContent);
                        OnMessageReceived?.Invoke(this, new WebsocketClientMessageReceivedEventArgs(this, msg));
                    }
                }
            }
            catch (Exception ex)
            {
                if (Helper.Log.IsErrorEnabled)
                    Helper.Log.Error("Websocket #" + connum + " " + ip + " Echec de lecture. " + ex.GetBaseException().Message + " - " + ex.GetBaseException().StackTrace);
                await CloseAsync();
            }
        }

        public async Task WriteAsync()
        {
            await Task.Yield();

            while (sock.IsConnected)
            {
                try
                {
                    if (outgoingQueue.Count > 0)
                    {
                        string data = null;
                        outgoingQueue.TryDequeue(out data);
                        
                        if (data != null)
                        {
                            await sock.WriteStringAsync(data, CancellationToken.None);
                        }
                    }
                    else
                    {
                        await Task.Delay(Helper.TaskDelay);
                    }
                }
                catch (Exception ex)
                {
                    if (Helper.Log.IsErrorEnabled)
                        Helper.Log.Error("Websocket #" + Connum + " " + ip + " Echec d'écriture. " + ex.GetBaseException().Message + " - " + ex.GetBaseException().StackTrace);
                }
            }
            if (Helper.Log.IsDebugEnabled)
                Helper.Log.Debug("Socket #" + this.Connum + " : Sortie de la boucle WriteAsync");
            await CloseAsync();
        }

```

Correct me if i'm wrong, but the 2 functions will run in dedicated thread right ?

if i replace all the task.run methodes in my code with creation of a new thread, i should have the same effect right ? because if i do it, then the code start to be veeeeery slooooow when the app need to send 100 messages to 100 clients very quickly...

i'm speding more and more time to other things than coding, and so i'm stuck with the habits of 10 years before... so maybe i'm wrong in lot of my code design :(

ps: i'm using message compression, but have bad performances event without.i'll remove it

**Comment by deniszykov** [comment]
TaskCreationOptions.LongRunning - this will create new thread on each call. Why you do that if you first statement in async method is 'await Task.Yield()' which mean 'fork this execution context and continue'. You could just call this.ReadAsync() and current thread will not be blocked.
```
                if (outgoingQueue.Count > 0)
                {
                    // ... send
                }
                else
                {
                    await Task.Delay(Helper.TaskDelay);
                }
```
This approach scales badly . It is better to use some kind of [async queue](WebSocketListener/blob/master/vtortola.WebSockets/Async/AsyncQueue.cs) or from [this](https://github.com/HellBrick/AsyncCollections) package or TPL dataflow or Rx.
```
while(isNotStopped)
{
    var message = await outgoingQueue.DequeueAsync();
   // ... send message 
}  
```

**Comment by warenbe** [comment]
mmmhhh yes i'll have a look on this
also i just though that i'm using .Invoke to fire all events, i suppose calling begininvoke might help... not sure because some events needs to be analysed synchronously.

**Comment by warenbe** [comment]
and for the Yield, i was not sure if it had the same effect. i'll remove the long running.

**Comment by warenbe** [comment]
Thanks to you i was able to solve the problem by using the package [https://github.com/HellBrick/AsyncCollections](url)


now it run without any problem on mono and it's faster than before. no more task.delay or thread.sleep. i also converted the thread used in the library 1 by Task.

i really understand better the task approach now :)
too bad lot of things are not async compatible in lot of package i use :(

CPU is now idling for my app when nothing is received/sent, before it was 6% per client connected...

![image](https://user-images.githubusercontent.com/25795188/34560452-0ccdfaaa-f146-11e7-91b2-8ad210463bd4.png)

**Comment by deniszykov** [comment]
welcome 👍
