### ISSUE TITLE
Allow setting of nat traversal 

### ISSUE THREAD

**Issue by andrewmd5** [deniszykov/WebSocketListener#16]
Allowing us to set the protection level of the socket might fix possible connectivity issues.  This can be done on two fronts

If you’re using TcpListener or UdpClient, then call AllowNatTraversal with a value of true.
```
var listener = new TcpListener(IPAddress.Any, 8000); 
listener.AllowNatTraversal(true); 
listener.Start();
```

And using raw sockets

Either way we need the ability to try and ensure connections to the target machine are successful and this helps.

**Comment by deniszykov** [comment]
Hi, I have added this feature for `.NET 4.5` platform in 4.1.6-alpha. `TcpTransport.IpProtectionLevel` could be changed with:
```
options.Transports.ConfigureTcp(tcp =>
{
    tcp.IpProtectionLevel = IPProtectionLevel.Unrestricted;
});
```
