### ISSUE TITLE
Add header to client ahead of time

### ISSUE THREAD

**Issue by andrewmd5** [deniszykov/WebSocketListener#2]
Hey there, fantastic work on this fork!

I'm trying to use the WebSocketClient implementation, however I'm not seeing an option to add custom headers to the client before the connecting request. 

Additionally I'd like to change the User-Agent. 

Any help is appreciated.

**Comment by deniszykov** [comment]
Hi! 
I have added request headers to ConnectAsync signature. You can check 6aab8acf6c09b70de8c10b8ab830cc6b99b41625 commit for details.
