### ISSUE TITLE
Issue using websocket client over/on IPv6 network

### ISSUE THREAD

**Issue by squinn7** [deniszykov/WebSocketListener#21]
Hello,

I am not sure where and how to begin with this one but I wanted to put the info out there to open up the issue. During our recent app store submission on iOS, apple was unable to connect to our testing system. The system is reached by a domain name however the issue seemed to be because apple tests over IPv6 networks. I have come across this issue in the past with apple so I was able to test locally and indeed found an issue when I tested myself. The app would connect okay if you were on a normal network but it would not connect on an IPv6 network.

The exception message is AccessDenied 

I was able to push through the submission by reverting to an older library for web socket communication but the issue remains unsolved.

I looked very briefly into it but wasn't really sure where something like this could be fixed. I am willing to help out if pointed in the right direction but for now I just want to put the info out for others to be aware.

**Comment by deniszykov** [comment]
Hi! You are using WebSocketClient on iOS? Which runtime? Version? Is it Mono or Unity? Is SSL involved?

**Comment by squinn7** [comment]
iOS, latest version at the time (11.2.5), We use Xamarin.Forms, so it is mono based. SSL was being utilized. We were using visual studio 15.6 at the time, so mono version should be Mono Framework 5.8.0.127 

I would assume the issue would also happen on Android in our configuration but I have not verified that.

**Comment by deniszykov** [comment]
SocketTransport.ConnectAsync() is method where TCP connection is establised. If you specify domain name instead of IP address, it will Socket.ConnectAsync with DnsEndpoint. This should work if DNS entry has AAAA record and server is listening for IPv6 connections.

Could you provide detailed error message?

**Comment by squinn7** [comment]
I can but it will take me some time to pull together an example. It is difficult to put a test device onto an ipv6 network.

Your second point is interesting, do you think the server configuration can cause it not to work? We have an older endpoint and a newer one and I believe it didn't work on either(I know our older one for sure didn't work as we use it for apple to do their testing) but I don't have deep knowledge of how it was all setup.

**Comment by squinn7** [comment]
I will say though with our older websocket client, we were able to connect to our test server without any config changes.

**Comment by deniszykov** [comment]
Emm... which client do you use? Do you connect via IPv6?

**Comment by squinn7** [comment]
We used Square.SocketRocket, which has a c# binding here https://github.com/mattleibow/square-bindings

This client was able to connect over the IPv6 network

**Comment by deniszykov** [comment]
I will look for DualMode feature of .NET Sockets (https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.dualmode(v=vs.110).aspx) and try to add it as soon as possible.

**Comment by squinn7** [comment]
Okay, that looks like that can solve the issue. I can help test if needed. Apple has a documentation for how to setup an IPv6 network in their [IPv6 support document](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html ). That is the only easy way I know of to test it.

**Comment by deniszykov** [comment]
I have updated package to version [4.2.1-alpha](https://www.nuget.org/packages/deniszykov.WebSocketListener/4.2.1-alpha). If it is ok, I will release it as 4.2.2 (stable).

You need to manually enable DualMode for you TCP transport:
```cs
options.Transports.ConfigureTcp(tcp =>
{
    tcp.DualMode = true;
});
```
And pass domain name in WebSocketClient.ConnectAsync("wss://mydomain.com/").

**Comment by squinn7** [comment]
Okay, I will see if I can test that this afternoon

**Comment by squinn7** [comment]
I was able to test that it works making that configuration change. I was able to connect to our test server over ipv4 networks and ipv6 networks. This is all of course via domain name.

**Comment by deniszykov** [comment]
Nice. I will release it!

**Comment by deniszykov** [comment]
Last time I tested DualMode on Mono it doesn't work. Seems they fix it.
