### ISSUE TITLE
WebSocketMessageReadNetworkStream can only start with a Text or Binary frame, not Continuation

### ISSUE THREAD

**Issue by imanushin** [deniszykov/WebSocketListener#26]
In case of working with Java Spring 5.0 Web Sockets, the following error was occurred:

```
WebSocketMessageReadNetworkStream can only start with a Text or Binary frame, not Continuation.
```

How this can be fixed?

This issue happens on the massive web socket messages receive, e.g. it is actual only for case, when multiple independent parallel connections (for the same socket client) receive ~10 000 messages.

**Comment by deniszykov** [comment]
related to https://github.com/vtortola/WebSocketListener/issues/135

**Comment by imanushin** [comment]
Yes, I added issues to the another project by mistake. I got the following error by using WebSocketListener v 4.2.4 with different servers: with Tomcat and Spring MVC and with Nerry and Spring Flux. Both servers got the same issue which can be suppressed by reconection.

I'm going to add more details into the log message if you have no objections
