### ISSUE TITLE
Remove assembly signing

### ISSUE THREAD

**Issue by imanushin** [deniszykov/WebSocketListener#27]
I sugest to remove assembly signing from the project, to avoid issues with singing key change in future.

log4net got popular issue in the past: https://haacked.com/archive/2012/02/16/changing-a-strong-name-is-a-major-breaking-change.aspx/

Please also see suggestion here: https://stackoverflow.com/questions/1197133/anything-wrong-with-not-signing-a-net-assembly

**Comment by deniszykov** [comment]
Hi @imanushin! This would be breaking change for everyone who use my assembly from signed assembly.
> In order to sign an assembly, any assemblies it depends upon must also be signed.

My assembly doesn't have un-signed dependencies, private key is published, so there is no point in un-signing it.

**Comment by imanushin** [comment]
agree
