### ISSUE TITLE
Use WebSocketDeflateExtension in WebSocketClient

### ISSUE THREAD

**Issue by ngyukman** [deniszykov/WebSocketListener#30]
hi, thanks for the nice library, right now I have problem when enabling Deflate in WebSocketClient

```csharp
var options = new WebSocketListenerOptions();

options.Standards.RegisterRfc6455(standard => standard.MessageExtensions.Add(new WebSocketDeflateExtension()));
var client = new WebSocketClient(options);
await client.ConnectAsync(uri, CancellationToken.None);
```

I have tried the above code to see if the client could enable the `permessage-deflate` but it fails to connect and returns 400 Bad Request, am I missing something to enable it in WebSocketClient?

**Comment by deniszykov** [comment]
Hi @ngyukman! Actually there is no extension negotiation in WebSocketClient, I forgot it ;) 
Implementation will took some time.

**Comment by ngyukman** [comment]
thanks!

I think it should be enabled by default and let the server to decide if compression is enabled or not

**Comment by deniszykov** [comment]
I have added extension negotiation in WebSocketClient! 🥳
