### ISSUE TITLE
[Question] Use RecyclableMemoryStream instead of buffer management

### ISSUE THREAD

**Issue by imanushin** [deniszykov/WebSocketListener#35]
Question: what do you think about reusing [RecyclableMemoryStream](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream) instead of custom BufferManager implementation?

So each Web Socket stream can have ```RecyclableMemoryStream``` internally, so it will just wrap real implementation.

Pros:
* We delegate byte management task to another component
* Clients of our library can set previously created RecyclableMemoryStreamManager for us (e.g. they will able to have single byte manager for whole application)

Cons:
* We will add one more external dependency

**Comment by deniszykov** [comment]
Hi @imanushin! [BufferManager](https://github.com/deniszykov/WebSocketListener/blob/master/vtortola.WebSockets/BufferManager.cs) is abstract class and could be set in `WebSocketListenerOptions` so any library user could use it's own `byte[]` pool class.

External dependencies in non-framework libraries are evil.
