### ISSUE TITLE
referencing System.Windows.Forms.dll

### ISSUE THREAD

**Issue by paulpach** [deniszykov/WebSocketListener#38]
When I import the dll  in Unity3d,  I get the following warning:

System.Windows.Forms.dll assembly is referenced by user code, but is not supported on StandaloneOSXUniversal platform. Various failures might follow.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

Why is this dll referencing System.Windows.Forms.dll?

**Comment by deniszykov** [comment]
Hi @paulpach! There is no references on **System.Windows.Forms.dll** in this library.
https://monosnap.com/direct/6gjMnX0yoRcDbNLuHmLTCRzEfwKU6g

**Comment by paulpach** [comment]
sorry,  I think this is in my code.  Thanks for the response

**Comment by paulpach** [comment]
Just in case anyone gets here looking for an answer:

This is a unity thing,  nothing wrong with the library.

It turns out that if you add a netstandard1.3 or netstandard2.0 dll to unity,  it will automatically add references to a dozen dlls  including System.Windows.Forms.dll  and then complain that your user code is using that dll.
