### ISSUE TITLE
SSL/TLS issues when port scanning

### ISSUE THREAD

**Issue by MattComb** [deniszykov/WebSocketListener#4]
Hi Denis, 

I have a working WebSocket Server, however, when port scanning occurs against the socket, I'm getting the following error message examples

1. A call to SSPI failed, see inner exception. - The token supplied to the function is invalid
2. A call to SSPI failed, see inner exception. - The client and server cannot communicate, because they do not possess a common algorithm

These errors appear to be due to a mismatch in TLS algorithm / version

The error is captured in the Observer OnError event, however after receiving the error, no more connections are accepted on the websocket server, so this is a problem.

I am using the following pattern:

                var chatSessionObserver = new ChatSessionsObserver(chatRoomManager);

                Observable.FromAsync(server.AcceptWebSocketAsync)
                    .Select(ws => new ChatSession(ws, chatRoomManager)
                    {
                        In = Observable.FromAsync<dynamic>(ws.ReadDynamicAsync)
                            .DoWhile(() => ws.IsConnected)
                            .Where(msg => msg != null),

                        Out = Observer.Create<dynamic>(ws.WriteDynamic)
                    })
                    .DoWhile(() => server.IsStarted && !cancellation.IsCancellationRequested)
                    .Subscribe(chatSessionObserver);

Have you seen this error before, and if so do you know how to protect against it.

Regards,

Matt.

**Comment by deniszykov** [comment]
I always thought Observable stop emitting new items when error occur. Do you restart observable after error?

**Comment by MattComb** [comment]
not currently.

I have applied the following:
.OnErrorResumeNext(Observable.Empty<ChatSession>())

It appears to work, do you see any problem with this approach. If ok, then this issue is not a bug

**Comment by deniszykov** [comment]
> do you see any problem with this approach. 

Actually I don't use Rx and can't appraise this approach.  
You could replace ```server.AcceptWebSocketAsync``` with 
```cs
async () => {
    while(server.IsStarted)
    {
        try
        {
            return await server.AcceptWebSocketAsync();
        }
        catch
        {
            // log connection error ...
        }
    }
    throw new Exception("Server is stopped"); // or return null;
}

**Comment by MattComb** [comment]
Thanks!
