### ISSUE TITLE
empty continuation frame

### ISSUE THREAD

**Issue by paulpach** [deniszykov/WebSocketListener#40]
I am writing messages like this:

```cs
using (var messageWriterStream = client.CreateMessageWriter(WebSocketMessageType.Binary))
{
    await messageWriterStream.WriteAsync(data, 0, data.Length, cancellation.Token);
    await messageWriterStream.FlushAsync(cancellation.Token);
    await messageWriterStream.CloseAsync();
}
```

This is generating 2 frames:

```cs
(672D0000) [FRAME->] Binary, len: 17, key: 0, flags: 
(672D0000) [FRAME->] Continuation, len: 0, key: 0, flags: FIN
```

This seems very wasteful, especially when nagle algorithm is turned off.   This could be just 1 frame with len 17 and FIN flag.

I understand that I could call WriteAsync many times,  so WriteAsync cannot set the FIN flag because it cannot tell if there will be more data.

Perhaps you could provide a function that writes a byte[] as a whole message ?    or a "WriteAndCloseAsync"  method that will set the FIN flag in the last frame?

**Comment by deniszykov** [comment]
Hi, it would be good enhancement. I will consider this.

**Comment by deniszykov** [comment]
I have added WriteAndCloseAsync in this fb355a85634afc606e026fc2118ffd2c57bc8787 commit. Feel free to test it.

**Comment by deniszykov** [comment]
added in [4.2.7](https://www.nuget.org/packages/deniszykov.WebSocketListener/4.2.7-alpha)
