### ISSUE TITLE
SSL Issue : Empty request line is received

### ISSUE THREAD

**Issue by warenbe** [deniszykov/WebSocketListener#41]
Hi 
the WS server works fine with WS: protocole
i want to add support for WSS: when the browser location is HTTPS

but i have this error when trying to connect **from firefox**

```
2019-01-16 19:33:00,332 214614 [10] ERROR WSServer.WebsocketServer - Impossible de lire les données de la connexion de transport : An established connection was aborted by the software in your host machine.
   à System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   à System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   à System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   à System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.StreamReader.ReadBuffer()
   à System.IO.StreamReader.ReadLine()
   à vtortola.WebSockets.WebSocketHandshaker.ReadHttpRequest(NetworkConnection clientStream, WebSocketHandshake handshake)
   à vtortola.WebSockets.WebSocketHandshaker.<HandshakeAsync>d__6.MoveNext()
2019-01-16 19:33:00,373 214655 [10] INFO  WSServer.WebsocketServer - Erreur de négociation Websocket : An established connection was aborted by the software in your host machine.
```
(repeat this error 3 times)

and this one when trying **from Chrome**

```
2019-01-16 19:34:24,620 298902 [25] ERROR WSServer.WebsocketServer - Empty request line is received. Probably connection is closed.
   à vtortola.WebSockets.WebSocketHandshaker.ParseGET(String line, WebSocketHandshake handshake)
   à vtortola.WebSockets.WebSocketHandshaker.ReadHttpRequest(NetworkConnection clientStream, WebSocketHandshake handshake)
   à vtortola.WebSockets.WebSocketHandshaker.<HandshakeAsync>d__6.MoveNext()
2019-01-16 19:34:24,677 298959 [21] ERROR WSServer.WebsocketServer - Empty request line is received. Probably connection is closed.
   à vtortola.WebSockets.WebSocketHandshaker.ParseGET(String line, WebSocketHandshake handshake)
   à vtortola.WebSockets.WebSocketHandshaker.ReadHttpRequest(NetworkConnection clientStream, WebSocketHandshake handshake)
   à vtortola.WebSockets.WebSocketHandshaker.<HandshakeAsync>d__6.MoveNext()
2019-01-16 19:34:24,771 299053 [21] INFO  WSServer.WebsocketServer - Erreur de négociation Websocket : Empty request line is received. Probably connection is closed.
```

**But then it works !**

So: 
on firefox: it does not works, FF try to connect 3 time without success at all
on Chrome: first connection get an error, but next one is OK

the certificate is self signed

How can i get this to work on both browser ? (without error) ?

Here is the configuration of the server: 

```
var bufferSize = 1024 * 8; 
                var bufferPoolSize = 100 * bufferSize; 
                var options = new WebSocketListenerOptions
                {
                    PingTimeout = TimeSpan.FromSeconds(60),
                    NegotiationTimeout = TimeSpan.FromSeconds(20),
                    PingMode = PingMode.LatencyControl,
                    ParallelNegotiations = 16,
                    NegotiationQueueCapacity = 256,
                    BufferManager = BufferManager.CreateBufferManager(bufferPoolSize, bufferSize),
                    Logger = WSLogger.Instance
                };
                options.Transports.ConfigureTcp(tcp =>
                {
                    tcp.BacklogSize = 100;
                    tcp.ReceiveBufferSize = bufferSize;
                    tcp.SendBufferSize = bufferSize;
                    tcp.SendTimeout = TimeSpan.FromSeconds(60);
                    tcp.ReceiveTimeout = TimeSpan.FromSeconds(60);
                    tcp.NoDelay = false;
                });
                options.Standards.RegisterRfc6455();

                Uri[] listenEndPoints = new Uri[1];

                listenEndPoints[0] = new Uri("wss://0.0.0.0:" + listenPort);
                if (certificate != "") //WSS
                {
                    X509Certificate2 cert = new X509Certificate2(certificate, certPassword);
                    options.ConnectionExtensions.RegisterSecureConnection(cert);
                    options.SupportedSslProtocols = SslProtocols.Tls12;
                    if (Helper.Log.IsInfoEnabled)
                        Helper.Log.Info("Using WSS");
                }
                server = new WebSocketListener(listenEndPoints, options);
```

**Comment by warenbe** [comment]
When i'm using firefox to connect to the server i get a different message: 

(sorry it's in french)

```
2019-01-16 19:18:07,246 275673 [26] ERROR WSServer.WebsocketServer - Échec d'un appel à SSPI, consultez l'exception interne.
   à System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   à System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   à System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   à System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à vtortola.WebSockets.WebSocketSecureConnectionExtension.<ExtendConnectionAsync>d__6.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à vtortola.WebSockets.Http.HttpNegotiationQueue.<NegotiateWebSocket>d__11.MoveNext()
```

it says "Faild of a call to SSPI, please consult the internal exception"

and the internal exception say "An unknown error occurred while processing the certificate"


the certificate is self signed and works find in apache.

**Comment by deniszykov** [comment]
There is an problem with WSS and Self-Signed certificates. There are two issues about this problem vtortola/WebSocketListener#104 #10 
Make sure you are properly handle (close/dispose) incoming WS connections from server.
And better to serve WSS by reverse-proxy like AWS/Azure Load Balancer, nginx, HAProxy

**Comment by warenbe** [comment]
Yes i saw that. it seems that the error message can be different between OS/browser… that's Strange

by doing a proxy you mean than the browser send the websocket connection request to the web server, and the web server communicate with the websocket server ?
if yes is it possible with Apache ?
considering that i have apache + my own process running with mono

do you have example of this ?

edit: like this?
https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

i'm not sure to understand… it means that apache crypt/uncrypt data before sending it to the websocket server ?
so currently i have a webpage connecting to my websocket server on port 20000 
and with proxy i'll have the same webpage connecting to apache on port 443 and apache will relay it to my websocket server on pot 20000 ?

**Comment by deniszykov** [comment]
> by doing a proxy you mean than the browser send the websocket connection request to the web server, and the web server communicate with the websocket server ?

Yes.  Browser -> Apache -> Your App (127.0.0.1:20000)

> if yes is it possible with Apache ?
> like this?

Looks like it.  ```ProxyPass "/any_prefix_path/"  "ws://127.0.0.1:20000"```

> it means that apache crypt/uncrypt data before sending it to the websocket server ?

Browser connect to your Apache. Apache do SSL handshaking, WS handshaking etc and do WS connection to your app. Then re-send all incoming messages between browser and your app.
> apache will relay it to my websocket server on pot 20000 ?

From browser side you need to connect to your normal address like `wss://example.com/` with prefix path `/any_prefix_path/`  (wss://example.com/any_prefix_path/) and all these WS connections will be proxied to your App at port 20000.

**Comment by warenbe** [comment]
Hi @deniszykov 

i took some time this evening to test the proxy
and it works!

for those who want the solution: 

Let's consider you have a process with the websocket server running on port 20000 on your server.

first, modify the apache configuration by adding the proxy in your virtualhost
Here is an example with my virtual hosts

```
VirtualHost *:80>
  ServerName pbx.localhost:80
  
  ProxyPreserveHost On
  ProxyRequests off
  SSLProxyEngine On
  ProxyPass /ws ws://localhost:20000 retry=0
  ProxyPassReverse /ws ws://localhost:20000 retry=0
  
  DocumentRoot "D:/Projets/NetBeans"
	<Directory "D:/Projets/NetBeans">
	    Options Indexes FollowSymLinks
		AllowOverride all
		Require all granted
	</Directory>
</virtualhost>

<VirtualHost *:443>
  SSLEngine on
  ServerName pbx.localhost:443
  
  SSLCertificateFile "D:\Apache24\certificats\asterisk.crt"
  SSLCertificateKeyFile "D:\Apache24\certificats\asterisk.key"
  
  
  ProxyPreserveHost On
  ProxyRequests off
  SSLProxyEngine On
  ProxyPass /ws ws://localhost:20000 retry=0
  ProxyPassReverse /ws ws://localhost:20000 retry=0
  
  DocumentRoot "D:/Projets/NetBeans"
	<Directory "D:/Projets/NetBeans">
	    Options Indexes FollowSymLinks
		AllowOverride all
		Require all granted
	</Directory>
</virtualhost>
```

Then, restart apache

modify your javascript solution : dont connect to websocket using "ws[s]://your-server-ip:20000", but connect using "ws[s]://your-server-ip[:443]/ws"
and it works ;)

And yes, so you're connected using WSS to a WS server through apache

i hope i did not made mistakes, but on my test machine it works.

**Comment by deniszykov** [comment]
I think you can use one prefix "ws" and one scheme in both ProxyPass directives (:80 and :443).
```ProxyPass /ws ws://localhost:20000 retry=0``` because connection between Apache and Your App is not protected.

**Comment by warenbe** [comment]
Yes i just edited my comment
it's even simplier ;)
thanks for helping me with this idea of proxy

**Comment by deniszykov** [comment]
> Yes i just edited my comment
> it's even simplier ;)
> thanks for helping me with this idea of proxy

Excellent!
