### ISSUE TITLE
Chrome (Opcode -1)

### ISSUE THREAD

**Issue by gusevvasily** [deniszykov/WebSocketListener#42]
Hello, @deniszykov 
I send message from client, and get this, in the section frames:
![screenshot_83](https://user-images.githubusercontent.com/21026700/51433330-1adf0000-1c59-11e9-955e-34fe6a39a9ce.png)
=============================================
![screenshot_80](https://user-images.githubusercontent.com/21026700/51431929-e0696900-1c40-11e9-9010-e9ad36b0b828.png)
After the connection is reset and connected again.
My code:
![screenshot_81](https://user-images.githubusercontent.com/21026700/51431933-01ca5500-1c41-11e9-9d52-9a59a3cc54c9.png)
(For your repository example code)

After testing different browsers, I came to the conclusion: chrome, opera, firefox, running windows 10, break the connection after each message sent by the server to the client. But in Safari on ios 12, everything is fine, 0% loss and fast speed...

Maybe this will help:
Protocol: WSS;
The client connects by ip, which comes with nginx and proximedia to local port by ws. here are the headers and parameters of proxying and connecting in the nginx file.
![screenshot_84](https://user-images.githubusercontent.com/21026700/51433591-94c5b800-1c5e-11e9-95ad-2813b67f1fdb.png)

Browser request and response headers (Chrome):
![screenshot_85](https://user-images.githubusercontent.com/21026700/51437546-cb2c2300-1cb0-11e9-9461-b4dd80eb2f74.png)

Thank.

**Comment by deniszykov** [comment]
Hi @GusevVasily!
You need to check you code for proper Closing/Disposing of messages and WS instances (look for examples and readme). Plus ensure there is no multi-thread access to this instances. Almous all types are not thread-safe and can't be used without proper synronization.

**Comment by gusevvasily** [comment]
Oh my god...
The problem was corrected by disabling register Deflate Compression...
![screenshot_96](https://user-images.githubusercontent.com/21026700/51489005-19781980-1db8-11e9-9d3f-8d420c966be6.png)
