### ISSUE TITLE
Are both browser and non-browser clients supported?

### ISSUE THREAD

**Issue by SameerRaina** [deniszykov/WebSocketListener#43]
hi,
this might be too basic a question, and if so, sorry for the trouble, but I wanted to know if WebSocketListener server works with both browser based and non-browser based clients(e.g. mobile games)? I know that depends on the port to be used but I wanted to be doubly sure.
thanks,
Sameer

**Comment by deniszykov** [comment]
Yes, it is designed by specification RFC 6455, so it could be used with any compatible client (almost any client).
