### ISSUE TITLE
Sending a custom close code to clients

### ISSUE THREAD

**Issue by trinitrotoluene** [deniszykov/WebSocketListener#45]
Hi- thanks for this awesome library, it's been very useful in my project so far. I've encountered a bit of a stumbling block when attempting to send close codes to clients. 

`WebSocket` does not have an overload for close codes in `CloseAsync()` and the `WebSocketRfc6455` implementation doesn't offer one either, instead just sending `WebSocketCloseReasons.NormalClose`. Looking at the code there doesn't seem to be a way to access the underlying Connection object since it's entirely internal, so I'm not entirely sure how to proceed from here.

Close codes (and reasons) are not optional in the RFC (5.1.1), insofar as I understand their wording, so it'd be quite useful to have a way to send them to clients.

If there is in fact no way to send these easily in the library, would you perhaps be open to a PR adding that overload?

**Comment by deniszykov** [comment]
Sounds reasonable. But there will be problems with 'message' because closing message is not supported inside Connection.CloseAsync() method. PR would be welcomed.
