### ISSUE TITLE
Feature Request: SocketClose event hook

### ISSUE THREAD

**Issue by weweilep** [deniszykov/WebSocketListener#47]
Along with the recently added WebSocketCloseReason, it would be helpful to have an event to hook into to handle socket closings, and the CloseReason could be a part of the event args.

**Comment by deniszykov** [comment]
I prefer no to use event in non-UI code. They leads to bad design and unpredictable control flow. 
End of incoming messages (null message) is an notification about WS closure.

**Comment by weweilep** [comment]
Fair enough, that you for the information.
