### ISSUE TITLE
[question] Disconnects

### ISSUE THREAD

**Issue by GentleRock** [deniszykov/WebSocketListener#48]
Hi Denis,
I have a very similar issue to what discussed in 'Dropped Connections'
#1 

What I do is to just run the samples: EchoServer and WebSocketClient
(using localhost for the client too). And it works.

But if I start debugging, or I use a Thread.Sleep(timespan) with a timespan value > 5-8000 secs instead than 400, I get disconnections, that clearly start from the server.

On the server side I use
`                PingTimeout = TimeSpan.FromSeconds(500), /*was 5*/
                NegotiationTimeout = TimeSpan.FromSeconds(500), /*was 5*/
                PingMode = PingMode.Manual,
`
but the problem stays.

This is important for me because I tend to debug, rather than trace, my application or your code in order to understand it.

A related question is about the Half Open connections check. How is it possible to disable it or increase the timespan between checks?

I'm using your latest version that I get by pressing the button 'Clone or download' and choosing 'Download ZIP'. Unfortunately I can't find a version number in your code.

Best Regards,
Marcello

**Comment by deniszykov** [comment]
Hi @marcello-pietrobon! 

### Timeouts

Actually I have no idea (beside Ping) why server-side would close connection after prolonged halted state.
You could set `WebSocketListenerOptions.Logger` and trace close reason (timeout, or socket error etc.).

Also there is a native [socket timeout](https://serverfault.com/questions/193160/which-is-the-default-tcp-connect-timeout-in-windows) on windows.

### Half opened connections

If you asking about '*It detects and disconnects half open connections.*' from original `vtortola/WebSocketListener` repo, I think it is `WebSocketListenerOptions.NegotiationTimeout` parameter. I didn't find any other code related to negotiation checks.
