### ISSUE TITLE
Deflation in version 4.2.7-alpha + throws "Header checksum illegal"

### ISSUE THREAD

**Issue by sam80180** [deniszykov/WebSocketListener#52]
Your custom inflator implementation seems to malfunction....

**Comment by deniszykov** [comment]
I will fix it. It should work.

**Comment by deniszykov** [comment]
I have failed to fix it, and I reverted it back to original code. 
Issue of original code is synchronous Flush/Write of DeflateStream, which couldn't be avoided.

**Comment by sam80180** [comment]
the deflation written by [vtortola](https://github.com/vtortola/WebSocketListener/tree/master/vtortola.WebSockets/Deflate) works just fine. Why not integrate it ?

**Comment by deniszykov** [comment]
> 
> 
> the deflation written by [vtortola](https://github.com/vtortola/WebSocketListener/tree/master/vtortola.WebSockets/Deflate) works just fine. Why not integrate it ?

original code use DeflateStream which end compression with is synchronous Flush/Write. Any synchronous operation blocks _Thread_ from _Thread Pool_. Synchronous Flush/Write cause synchronous write to Socket which could block calling thread for long period of time.

**Comment by sam80180** [comment]
i just close the DeflateStream after every write operation, so thread doesn't block.
