### ISSUE TITLE
Support for Http Basic Authentication

### ISSUE THREAD

**Issue by TechAspirant** [deniszykov/WebSocketListener#53]
Do it supports Http Basic Authentication ?

**Comment by deniszykov** [comment]
Hi, you can set ```WebSocketListenerOptions.HttpAuthenticationCallback``` and perform any header-based authentication including [Basic](https://tools.ietf.org/html/rfc7617).

**Comment by TechAspirant** [comment]
Can you share a small piece of code showing how to use HttpAuthenticationCallback ?

**Comment by deniszykov** [comment]
here is example:
```cs
HttpAuthenticationHandler = async (request, response) =>
{
    var authorization = request.Headers[RequestHeader.Authorization];
    if (string.IsNullOrEmpty(authorization))
    {
        return false; // no header
    }
    var typeAndCredentials = authorization.Split(' ');
    if (typeAndCredentials.Length != 2 || !string.Equals(typeAndCredentials[0], "Basic", StringComparison.OrdinalIgnoreCase))
    {
        return false; // invalid header
    }

    var userAndPassword = Encoding.GetEncoding("ISO-8859-1").GetString(Convert.FromBase64String(typeAndCredentials[1])).Split(':');
    if (userAndPassword.Length != 2)
    {
        return false; // invalid username/password pair
    }

    // check username in userAndPassword[0]
    // check password in userAndPassword[1]

    request.Items["User"] = new GenericPrincipal(new GenericIdentity(userAndPassword[0]), new string[0]);
    return true;
}
```

**Comment by bmjames** [comment]
Is it possible to set a `WWW-Authenticate` header in an Unauthorized response, in case the client does not automatically provide credentials? The API seems to allow modifying the `Headers` collection of the response, but I've tried this and it does not appear to have any effect on the eventual response.

**Comment by deniszykov** [comment]
Currently headers from response are ignored. But I could add them to response in next release.
