### ISSUE TITLE
Websocket performance on mono + linux

### ISSUE THREAD

**Issue by warenbe** [deniszykov/WebSocketListener#57]
Hi 
this is a question, not a bug...
i'm sending a file using the websocket (encoded in base64 for simple management). the file is 8MB large. 
when i'm sending it locally, on my windows computer, running both server and javascript client on the same computer, the file is sent immediatly. 
now, if i'm running the server on Linux using mono 6, sending 8MB takes.... 56 seconds !
this is on local network, so, ok, it might take few seconds, not 56...

on the javascript console, i see that the whole file is sent immédiatly
if i open a wireshark , i see that the whole file is sent within a second... i clearly see all the request and all the ACK from the server.
but on the server, it seems that this code takes 56s: 

```
WebSocketMessageReadStream stream = await sock.ReadMessageAsync(cancelSource.Token);
if (stream != null && stream.MessageType == WebSocketMessageType.Text)
{
  sw.Restart();
  using (StreamReader sr = new StreamReader(stream, sockEncoding))
  {
    msgContent = await sr.ReadToEndAsync();
  }
  await stream.CloseAsync();
  sw.Stop();
}

```
any idea about why this code takes so much time ? 
do you think this is a problem with linux, mono? both?

**Comment by deniszykov** [comment]
I have problems with `Socket` on Mono (very poor performance) in past and I have reported memory corruption with Socket when load is high.
So only viable solution for Mono/Linux is Unix Sockets + Nginx,HAProxy,etc.
This is main reason why I made this fork, for WebSockets on Linux/Mono via Unix Sockets.

**Comment by warenbe** [comment]
so if i get you, something should handle the websocket (like for example apache?) and then work with unix socket ?
do you have an example of how to do it using apache ? i'm currently using apache websocket proxy

**Comment by deniszykov** [comment]
From application side it is easy:
```cs
var options = new WebSocketListenerOptions();
// register unix socket transport
options.Transports.RegisterUnixSockets(unix =>
{
    // setup buffers and other stuff
});
var listenEndPoints = new Uri[] {
    new Uri("unix:/var/myapp/listen.ws"), // change Unix Socket path here
};

// starting the server
var server = new WebSocketListener(listenEndPoints, options);
server.StartAsync().Wait();

// or set proper permissions for other apps to access
Mono.Unix.Native.Syscall.chmod("/var/myapp/listen.ws", Mono.Unix.Native.FilePermissions.ACCESSPERMS);
```

as from Apache-side I have no knowledge how to properly proxy WS.

UPD: Apache can serve via Unix Domain Sockets ->https://serverfault.com/questions/767071/proxypass-a-websocket-connection-to-a-unix-socket

**Comment by warenbe** [comment]
Thanks
i'll check that and get back to you if i succeed.
is it possible to add both TCP + unix socket as transport ?

**Comment by deniszykov** [comment]
>is it possible to add both TCP + unix socket as transport ?

yes, just specify multiple `listenEndPoints` 
```cs
options.Transports.ConfigureTcp(tcp =>{
    // setup buffers and other stuff like BacklogSize
});
options.Transports.RegisterUnixSockets(unix =>
{
    // setup buffers and other stuff like BacklogSize
});

var listenEndPoints = new Uri[] {
    new Uri("unix:/var/myapp/listen.ws"), // change Unix Socket path here
    new Uri("ws://localhost") // will listen both IPv4 and IPv6
};
```

**Comment by warenbe** [comment]
so far, i've very bad result.
i'm not sure about my apache proxy settings...
but i see logs from my app with a crash

any idea about this crash ?

```
2020-09-08 15:06:00,891 106693 [Thread Pool Worker] DEBUG WSServer.WebsocketServer - Accept from 'UnixSocketListener, /run/amiserv.sock' has failed.
2020-09-08 15:06:00,900 106702 [Thread Pool Worker] ERROR WSServer.WebsocketServer - Cannot be empty.
Parameter name: filename
  at Mono.Unix.UnixEndPoint..ctor (System.String filename) [0x00021] in <3aac8f2e45934fbc80077b6a92a73a67>:0
  at Mono.Unix.UnixEndPoint.Create (System.Net.SocketAddress socketAddress) [0x0005f] in <3aac8f2e45934fbc80077b6a92a73a67>:0
  at System.Net.Sockets.Socket.get_RemoteEndPoint () [0x00036] in <8a0944092ae944f79161e3ab1237b7dd>:0
  at vtortola.WebSockets.Transports.Sockets.SocketListener.AcceptSocketAsConnection (System.Threading.Tasks.Task`1[TResult] acceptTask, System.Net.EndPoint acceptEndPoint) [0x00065] in <f54b5b06d20c46d8aae0f5bcb4adaecf>:0
  at vtortola.WebSockets.Transports.Sockets.SocketListener.AcceptConnectionAsync () [0x00169] in <f54b5b06d20c46d8aae0f5bcb4adaecf>:0
```

**Comment by deniszykov** [comment]
Looks like this bug in Mono, probably fixed in fresh versions. 
I can make try/catch workaround for it in `AcceptSocketAsConnection`, still u get no valid `connection.RemoteEndPoint` if you need it.

**Comment by deniszykov** [comment]
Found source of error:
```
            if (this.log.IsDebugEnabled)
                this.log.Debug($"New socket accepted. Remote address: '{socket.RemoteEndPoint}', Local address: {socket.LocalEndPoint}.");
```

You can workaround it by disabling "Debug" logging for a while. A made package update some later.

In other places there is already try/catch wrapped code. Which gives `WebSocketHttpRequest.NoAddress` in case of error.

**Comment by warenbe** [comment]
ho yes you're right... i made for TCP at first, so i was displaying the source of the request in my code also
i need to remove this in case of unix socket... it does not have sense 
i'll remove the debug for my test at first.

**Comment by warenbe** [comment]
i removed the line from the code, and now i have a better result... but its not working
but i think this is my apache config that is failing... 
still searching why.

**Comment by warenbe** [comment]
ok i got it working ;)

now sending files takes: 
1MB = 1 seconde
9MB = 6 secondes
20MB = 16 secondes
50MB = 36 secondes

this is without any optimization, sending as base64 string (so, really not optimized...)

to get it working, i had to add this to my apache config: 

```
ProxyPreserveHost On
ProxyRequests off
ProxyPass /ws unix:///run/mysocket.sock|ws://localhost:65535
ProxyPassReverse /ws unix:///run/mysocket.sock|ws://localhost:65535
```
the strange |ws://localhost:65535: i don't understand the utility of this. but apparently the proxy know if it must handle the request based on the protocol string in the |ws://. If you set ws://localhost for example, it does not work. the uri must exist, but without any tcp server running on it. So i set port 65535 and it worked. 

the socket file must be readable/writable by apache (set the right after socket creation, so after the server has started... not before like me ;) )
