### ISSUE TITLE
WebSocketClient does not return acknowledgement for server-initiated close frames.

### ISSUE THREAD

**Issue by weweilep** [deniszykov/WebSocketListener#59]
Observed behavior (4.2.10):

1. Server sends CloseFrame
2. WebSocketClient receives CloseFrame and immediately closes without sending an acknowledgement.  (Confirmed via debug logger that only an inbound frame is logged.)

Expected behavoir:

1. Server sends CloseFrame
2. WebSocketClient sends acknowledgement CloseFrame
3. WebSocketClient closes

Relevant bit from RFC 6455 5.1.1:

> If an endpoint receives a Close frame and did not previously send a
>    Close frame, the endpoint MUST send a Close frame in response.  (When
>    sending a Close frame in response, the endpoint typically echos the
>    status code it received.)

**Comment by deniszykov** [comment]
Hi @weweilep! I will see what can be done.

**Comment by deniszykov** [comment]
Added close frame reply for unsolicited close frame.
[4.2.11](https://www.nuget.org/packages/deniszykov.WebSocketListener/4.2.11)

**Comment by weweilep** [comment]
@deniszykov thank you for the quick response, however, the 4.2.11 release appears to have released with bad library files.  Each included dll is only 5KB and has no external symbols (whereas previous releases were ~220KB).

**Comment by deniszykov** [comment]
Thanks for mentioning. MS Team changed build/pack routine and IL Repack task has failed. 
Re-released as [4.2.13](https://www.nuget.org/packages/deniszykov.WebSocketListener/4.2.13)

**Comment by weweilep** [comment]
@deniszykov This still seems to have unexpected behavior.  Now, according to the logger, there is an outgoing frame, but no incoming frame is sent to the read stream before it, and it results in a "Read operation on WebSocket stream is failed. More detailed information in inner exception." exception on the read loop.  Edit: Inner exception text: "An existing connection was forcibly closed by the remote host"

So while you handled the outgoing frame correctly, you changed the read stream behavoir that introduced a different issue.  It no longer ends in a null received message, but instead an exception.

**Comment by deniszykov** [comment]
It seems that in order to correctly implement the closing handshake, it is necessary to seriously rewrite control frame processing and close states. It would take a day or two.

**Comment by weweilep** [comment]
I should note, if you consider it, System.Net.Websockets handles CloseFrame as a MessageType (separate from Binary/Text).  That might be a breaking change for your implementation though, as that could potentially mean your stream doesn't end with a null stream, but instead a read with a close frame.  But you could still manually do a null readstream close after handling the MessageType.Close frame for compatibility.

**Comment by deniszykov** [comment]
I avoid to introduce big changes into API. Users can get the behavior of a "System.Net.Websockets" from a "System.Net.Websockets". Which were re-written in .NET Core. 

I have [added](https://github.com/deniszykov/WebSocketListener/commit/12d58e02dd9de4587594c5f1b53537795321a641) half-closed states and proper close handshake. Manual tests would take some time.
