### ISSUE TITLE
Error parsing Infinity

### ISSUE THREAD

**Issue by MattComb** [deniszykov/WebSocketListener#6]
I decided to finally get around to testing the disconnect issue today, but unfortunately ran into something new.

I am running the RxWebSocketChatServer and connecting to it using 2 connections.

The first message from each connection causes an error to appear in the console:

Rx Chat Server started at 0.0.0.0:8001
ChatJoinMessage: Error parsing Infinity value. Path '', line 1, position 1.
ChatMessage: Error parsing Infinity value. Path '', line 1, position 1.
ChatJoinMessage: Error parsing Infinity value. Path '', line 1, position 1.
ChatMessage: Error parsing Infinity value. Path '', line 1, position 1.

I have searched for the word Infinity but can't find it in the source code.

subsequent messages do not get sent to each connection.

error is caught in the CHatMessageHandler error event.

        public void OnError(Exception error)
        {
            Console.WriteLine("ChatMessage: " + error.Message);
            _chatRoomManager.RemoveFromRoom(_session);
        }

n.b. I set PingMode to manual but that made no difference.

**Comment by deniszykov** [comment]
Hi Matt! This is [JSON.NET exception](https://github.com/Wox-launcher/Wox/issues/1208). Probably related to content of WS messages. Please log and check content of messages when error occurs, maybe it will reveal source of problem.

**Comment by MattComb** [comment]
Ah! of course! I remember seeing that the code in your repository vs the code in vlads is different for this sample project. I believe yours automatically assumes a JSON object. Ill modify and continue. Thanks!

**Comment by deniszykov** [comment]
Actually I only maintain  ```EchoServer```, ```MonoEchoServer``` and ```WebSocketClient``` examples. If you fix RxWebSocketChat I will be glad to accept that fixes as Pull Request (or copy&pasted code).

**Comment by MattComb** [comment]
sure, happy to help.
