### ISSUE TITLE
Connection problems after SocketException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Alexxx8289** [deniszykov/WebSocketListener#62]
After a few connection error(An existing connection was forcibly closed by the remote host), the websocket server no longer accepts incoming connections. How can i make my server keep working?
.....
        static async Task AcceptWebSocketClients(WebSocketListener server, CancellationToken token)
        {
            string strDebug = "";
            while (!token.IsCancellationRequested)
            {
                try
                {
                    strDebug = "1";
                    var ws = await server.AcceptWebSocketAsync(token).ConfigureAwait(false);
                    strDebug = "2";
                    if (ws == null)
                        continue;
                    strDebug = "3";
                    var v = Task.Run(() => HandleConnectionAsync(ws, token));
                    strDebug = "4";
                }
                catch (Exception aex)
                {
                    var ex = aex.GetBaseException();
                    if (ex.Message != "Negotiation timeout")
                        Debug.Print("Error Accepting client: " + ex.GetType().Name + ": " + ex.Message);
                }
            }
        }
.......

As you can see I managed the error of the task, but after a few losses of connections it doesn't do anything anymore .... It doesn't accept any more connections

![image](https://user-images.githubusercontent.com/102237625/159731121-07066da1-ce8b-4566-89dd-5210187a4363.png)

**Comment by deniszykov** [comment]
Hi @Alexxx8289.
```cs
if (ws == null)
continue;
```
This is kinda wrong. Because `ws == null` when server is close/disposed and receive loop should be stopped.

Do you provide `WebSocketListenerOptions.Logger`? This could show reason why no more connections are accepted.
Also you must ensure disposing of accepted websockets in `HandleConnectionAsync` even if error occurs.

**Comment by Alexxx8289** [comment]
Hi, 
thank you very much for the quick reply.
I put ws == null as in the example because in some cases the AcceptWebSocketAsync returned null. But I was able to continue working anyway.

I had always worked with the old version (2.2.4). But I have these problems, so I also tried your latest version but always with the same results.

WebSocketListenerOptions.Logger is set to NullLogger.Instance.
Yes in HandleConnectionAsync i dispose all websocket..
.....
            finally
            {
                try
                {
                    if (ws != null)
                    {
                        if (ws.IsConnected)
                            ws.Close();
                    }
                }
                catch { }
                ws.Dispose();
                ws = null;
            }

Regards,
Alexxx

**Comment by deniszykov** [comment]
Please replace `WebSocketListenerOptions.Logger` with your logger and review log for messages.

**Comment by Alexxx8289** [comment]
Hi,
sorry for last reply...
below you can find mi log(i used vtortola 2.2.4)


31/03/2022 09:55:44|%|HttpNegotiationQueue.WorkAsync (Writting error esponse) failed because: (Exception): Impossibile scrivere dati sulla connessione di trasporto: Connessione in corso interrotta forzatamente dall'host remoto.|%|   in System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   in System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   in System.IO.StreamWriter.Flush()
   in vtortola.WebSockets.WebSocketHandshaker.WriteHttpResponse(WebSocketHandshake handshake, Stream clientStream) in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets\Http\WebSocketHandshaker.cs:riga 134
   in vtortola.WebSockets.WebSocketHandshaker.<HandshakeAsync>d__0.MoveNext() in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets\Http\WebSocketHandshaker.cs:riga 65|%|0|%|
31/03/2022 09:55:45|%|LatencyControlPing.StartPing failed because: (Exception): Cannot write on WebSocket|%|   in vtortola.WebSockets.Rfc6455.WebSocketConnectionRfc6455.<WriteInternalAsync>d__20.MoveNext() in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets.Rfc6455\WebSocketConnectionRfc6455.cs:riga 474
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   in vtortola.WebSockets.Rfc6455.LatencyControlPing.<StartPing>d__0.MoveNext() in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets.Rfc6455\Ping\LatencyControlPing.cs:riga 45|%|0|%|
31/03/2022 09:55:46|%|HttpNegotiationQueue.WorkAsync (Writting error esponse) failed because: (Exception): Impossibile scrivere dati sulla connessione di trasporto: Connessione in corso interrotta forzatamente dall'host remoto.|%|   in System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   in System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   in System.IO.StreamWriter.Flush()
   in vtortola.WebSockets.WebSocketHandshaker.WriteHttpResponse(WebSocketHandshake handshake, Stream clientStream) in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets\Http\WebSocketHandshaker.cs:riga 134
   in vtortola.WebSockets.WebSocketHandshaker.<HandshakeAsync>d__0.MoveNext() in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets\Http\WebSocketHandshaker.cs:riga 65|%|0|%|
31/03/2022 09:55:46|%|HttpNegotiationQueue.WorkAsync (Writting error esponse) failed because: (Exception): Impossibile scrivere dati sulla connessione di trasporto: Connessione in corso interrotta forzatamente dall'host remoto.|%|   in System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   in System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   in System.IO.StreamWriter.Flush()
   in vtortola.WebSockets.WebSocketHandshaker.WriteHttpResponse(WebSocketHandshake handshake, Stream clientStream) in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets\Http\WebSocketHandshaker.cs:riga 134
   in vtortola.WebSockets.WebSocketHandshaker.<HandshakeAsync>d__0.MoveNext() in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets\Http\WebSocketHandshaker.cs:riga 65|%|0|%|
31/03/2022 09:56:18|%|WebSocketConnectionRfc6455.Close failed because: (Exception): Cannot write on WebSocket|%|   in vtortola.WebSockets.Rfc6455.WebSocketConnectionRfc6455.WriteInternal(ArraySegment`1 buffer, Int32 count, Boolean isCompleted, Boolean headerSent, WebSocketFrameOption option, WebSocketExtensionFlags extensionFlags) in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets.Rfc6455\WebSocketConnectionRfc6455.cs:riga 440
   in vtortola.WebSockets.Rfc6455.WebSocketConnectionRfc6455.Close(WebSocketCloseReasons reason) in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets.Rfc6455\WebSocketConnectionRfc6455.cs:riga 490|%|0|%|
31/03/2022 09:56:20|%|WebSocketConnectionRfc6455.Close failed because: (Exception): Cannot write on WebSocket|%|   in vtortola.WebSockets.Rfc6455.WebSocketConnectionRfc6455.WriteInternal(ArraySegment`1 buffer, Int32 count, Boolean isCompleted, Boolean headerSent, WebSocketFrameOption option, WebSocketExtensionFlags extensionFlags) in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets.Rfc6455\WebSocketConnectionRfc6455.cs:riga 440
   in vtortola.WebSockets.Rfc6455.WebSocketConnectionRfc6455.Close(WebSocketCloseReasons reason) in c:\Users\aleg\Desktop\VTortola\WebSocketListener-Version-2.2.4\vtortola.WebSockets.Rfc6455\WebSocketConnectionRfc6455.cs:riga 490|%|0|%|

After these errors the clients are no longer able to connect. I have to close everything and restart the application

Best Regards,
Alexxx

**Comment by deniszykov** [comment]
Do you use `deniszykov.WebSocketListener` package or `vtortola.WebSocketListener`? Because both packages are sharing same code, but not implementation. If you use  `vtortola.WebSocketListener` you should report this bug to another repository.
If you use  `deniszykov.WebSocketListener` make sure to use last version `4.2.14` because some negotiation queue bugs are fixed in last versions.

**Comment by Alexxx8289** [comment]
I have encountered the problem with both versions. This log is from vtortola version 2.2.4, because I can compile it with VS2013

**Comment by deniszykov** [comment]
Sorry I can't help with `vtortola.WebSocketListener` because it is different packet. I'm only maintain  `deniszykov.WebSocketListener`. 
Please provide as much log as possible from `deniszykov.WebSocketListener`  package.

**Comment by Alexxx8289** [comment]
Hello,
I solved it by compiling my project(with your deniszykov.WebSocketListener) with visual studio 2022 instead of visual studio 2013.
I just have one more question, if I set the buffer size to 16KB instead of 8KB an exception is thrown:
**vtortola.WebSockets.WebSocketException: 'vtortola.WebSockets.DefaultBufferManager.16384 must be bigger or equals to SendBufferSize. Actual value of SendBufferSize: 8192'**

below my code....

.....
                var endpoint = new IPEndPoint(IPAddress.Any, 6969);
                var bufferSize = 1024 * 16; // 16KB instead 8KiB          <-------------------------------------------------
                var bufferPoolSize = 500 * bufferSize; // 800KiB pool

                var options = new WebSocketListenerOptions
                {
                    SubProtocols = new[] { "text" },
                    PingTimeout = TimeSpan.FromSeconds(30),
                    NegotiationTimeout = TimeSpan.FromSeconds(30),
                    PingMode = PingMode.Manual,
                    ParallelNegotiations = 16,
                    NegotiationQueueCapacity = 256,
                    BufferManager = vtortola.WebSockets.BufferManager.CreateBufferManager(bufferPoolSize, bufferSize),
                };

                options.Standards.RegisterRfc6455(factory =>
                {
                    factory.MessageExtensions.RegisterDeflateCompression();
                });
                // configure tcp transport
                options.Transports.ConfigureTcp(tcp =>
                {
                    tcp.BacklogSize = 1000; // max pending connections waiting to be accepted
                    tcp.ReceiveBufferSize = bufferSize;
                    tcp.SendBufferSize = bufferSize;
                });

......

what am I wrong?

**Comment by deniszykov** [comment]
Hi. There's a wrong error check in `WebSocketListenerOptions`. And bad error message. I have fixed them in v4.2.15. But you could workaround this error in previous versions by setting `WebSocketListenerOptions.SendBufferSize` to `bufferSize`.

**Comment by Alexxx8289** [comment]
Hi, 
great, now it works!!!
Another question: why if i change bufferpool size to 1000 instead 500 an exception is thrown:
**System.ArgumentOutOfRangeException: 'poolLimit > 0
Parameter name: poolSizeLimit'**

...........
                var bufferSize = 1024 * 16; // 8KiB
                var bufferPoolSize = 1000 * bufferSize; // 800KiB pool     <--------------------------------
                var options = new WebSocketListenerOptions
                {
                    SubProtocols = new[] { "text" },
                    PingTimeout = TimeSpan.FromSeconds(30),
                    NegotiationTimeout = TimeSpan.FromSeconds(30),
                    PingMode = PingMode.Manual,
                    ParallelNegotiations = 16,
                    NegotiationQueueCapacity = 256,
                    SendBufferSize = bufferSize,
                    BufferManager = vtortola.WebSockets.BufferManager.CreateBufferManager(bufferPoolSize, bufferSize),
                };
                options.Standards.RegisterRfc6455(factory =>
                {
                    factory.MessageExtensions.RegisterDeflateCompression();
                });
                // configure tcp transport
                options.Transports.ConfigureTcp(tcp =>
                {
                    tcp.BacklogSize = 1000; // max pending connections waiting to be accepted
                    tcp.ReceiveBufferSize = bufferSize;
                    tcp.SendBufferSize = bufferSize;
                });

                intLastConnection = Convert.ToInt32((DateTime.Now.Ticks - dteReferenceTimeReboot.Ticks) / 10000);

                // starting the server
                var server = new WebSocketListener(endpoint, options);
                server.StartAsync().Wait();

.......


what am I wrong?

**Comment by deniszykov** [comment]
Also fixed in `v4.2.15`. There was some wrong code regarding buffer manager.

**Comment by Alexxx8289** [comment]
Hi,
with the new version almost everything works better, now I only have a lot of errors like this:

Error Accepting client: 1 - WebSocketException: Empty request line is received. Probably connection is closed.
at vtortola.WebSockets.WebSocketHandshaker.ParseGET(String line, WebSocketHandshake handshake)
   at vtortola.WebSockets.WebSocketHandshaker.ReadHttpRequest(NetworkConnection clientStream, WebSocketHandshake handshake)
   at vtortola.WebSockets.WebSocketHandshaker.<HandshakeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at vtortola.WebSockets.WebSocketListener.<AcceptWebSocketAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at U_Sun.frmMain.<AcceptWebSocketClients>d__28.MoveNext() in E:\SW\U_Sun\U_Sun(NUOVA VERSIONE VTORTOLA 3.0)\U_Sun\U_Sun\frmMain.cs:line 133


What am I wrong? how can i correct?

Regards,
Alexxx

**Comment by deniszykov** [comment]
Yep, it is normal. If you didn't ignore TCP connection/disconnections errors in logging, It would be 99% of your log. Log these if you need to debug.
For example, Chrome likes to do connection probing. Or network scanners open/close connection to random ports just for sake of scanning.
