### ISSUE TITLE
.NET Core compatibility?

### ISSUE THREAD

**Issue by gwalschl** [deniszykov/WebSocketListener#7]
Hi Denis,

Is this library .NET core compatible today?  If not, are there plans for this in the near future?

Thanks!

**Comment by deniszykov** [comment]
Hi! It was compiled against .NET Standard 1.3 but I never tested it under .NET Core. Try [last one](https://www.nuget.org/packages/deniszykov.WebSocketListener/4.1.1-beta) version of package.

**Comment by gwalschl** [comment]
OK, great.  I'll give that a try some time soon.  Sorry about all these questions, but also wondering how thread safe this library is.  Can different threads perform reads and writes to the WebSocket class at the same time?  Or under what conditions do I need to use a mutex?  Simultaneous reads/writes or all operations?

Thanks again!

**Comment by deniszykov** [comment]
>but also wondering how thread safe this library is.

It is safe in terms of wrong API usage. It throws exceptions if you try to write/read simultaneously from several threads. So you need ensure single reader/writer with Rx, TPL Dataflow or simple write/read loop. You can read while writing or write while reading. Other operations are thread safe.

Here an [example](https://github.com/deniszykov/WebSocketListener/blob/master/Samples/EchoServer/Program.cs) - `AcceptWebSocketsAsync`

**Comment by gwalschl** [comment]
Great, thanks again for all your help.  Last thing is I'd like to confirm that the way the library works.  There is a single physical port associated with starting the server.  That single TCP port can handle traffic from multiple clients.  When a user of your library accepts an incoming connection request, somehow the WebSocket object returned from the AcceptWebSocketsAsync call knows what client it's associated with?  Is that correct?  This means that if your server is servicing multiple connections, there's nothing extra a user of the library needs to do to ensure that the reply goes to the correct client, the library just routes it correctly for you?

Thanks again for your helpful responses!

**Comment by deniszykov** [comment]
TCP connections are distinguished by [Local Endpoint & Remote Endpoint] pairs. Each connected WebSocket instance has [Socket](https://msdn.microsoft.com/en-US/library/system.net.sockets.socket(v=vs.110).aspx) which represents a TCP Connection. You can't access to Socket but you can access `RemoteEndpoint` and `LocalEndpoint` of [WebSocket](https://github.com/deniszykov/WebSocketListener/blob/master/vtortola.WebSockets/WebSocket.cs) class to identify your clients. And yes, you don't need to any extra work, you can treat each WebSocket instance as a client.

P.s. LocalEndpoint and RemoteEndpoint stuff has meaning for TCP Connections while Unix Domain Sockets and Named Pipes transports doesn't have any information about connected client.

**Comment by gwalschl** [comment]
Thanks for being so responsive!  I think I'll move forward with it.
