### ISSUE TITLE
URL question

### ISSUE THREAD

**Issue by gwalschl** [deniszykov/WebSocketListener#8]
First off, great library and fork!  I am very happy so far!

Sorry about the newbie question, but I have a legacy app not written by me that (don't know the technology behind it) apparently accepts WebSocket command messages on different service URLs (for example, one command is sent to ws://host:port/ws/messages another is ent to ws://host:port/status, etc.).

I am trying to mock this server's behavior but I'm not sure how to support this kind of behavior on the server side.  It looks like the WebSocketListener has a constructor that takes an array of Uri so that looks promising.  However, I'm not sure how the processing of those commands differs from the single listen endpoint.  Also, not sure how the code using WebSocketClient to connect to server needs to change.

Can you point me to any examples that illustrate how to code client and server for this use model?
  Any help greatly appreciated!

**Comment by deniszykov** [comment]
Hi @gwalschl! To handle WebSockets at different paths you need to bind one url "ws://host:port/" because 'path' part of url is ignored. WebSocket request is based  HTTP request and you can access HTTP request parameters at `WebSocket.HttpRequest`.

```
 var webSocket = await server.AcceptWebSocketAsync(cancellation).ConfigureAwait(false);
if (webSocket == null)
    return;
switch (webSocket.HttpRequest.RequestUri.LocalPath)
{
    case "messages":
        break;
    case "status":
        break;
}
```

**Comment by gwalschl** [comment]
Thanks for the reponse.  Sorry about my a lot of basic questions, but I'm still a bit new on this stuff and not clear.  

On server side I am doing this

    var options = new WebSocketListenerOptions();
    options.Standards.RegisterRfc6455();
    var server = new WebSocketListener(new IPEndPoint(IPAddress.Any, 50002), options);
    await server.StartAsync();

In your example, you show doing a switch on server side after accepting a new client connection.  In the client code, the only place I see where a Uri can be entered is in WebSocketClient.ConnectAsync().  So, I tried to connect with different URLs (same host/port) like

    WebSocket webSocket = await client.ConnectAsync(new Uri("ws://localhost:50002/"), cts.Token);
    WebSocket webSocketX = await client.ConnectAsync(new Uri("ws://localhost:50002/ws/x"), cts.Token);
    WebSocket webSocketY = await client.ConnectAsync(new Uri("ws://localhost:50002/ws/y"), cts.Token);
    WebSocket webSocketZ = await client.ConnectAsync(new Uri("ws://localhost:50002/ws/z"), cts.Token);

only the first one is accepted on the server side.    Given that, where/how do I specify URLs on client side that affect server side switch statement as in your example?  I don't see where I can specify a Uri when sending a message from client.  For sending, I'm just doing this

        using (var messageWriter = ws.CreateMessageWriter(WebSocketMessageType.Text))
        {
            using (var sw = new StreamWriter(messageWriter, Encoding.UTF8))
            {
                await sw.WriteAsync(message);
            }
        }

Is the issue that on each call on client side I have to call ConnectAsync() with a different URL and then dispose of that on a per call basis?  Right now I'm making one long lived connection on client.  I would hope I wouldn't have to make new connections on each request.

Again, sorry for the newbie questions, but I'm confused still...

**Comment by deniszykov** [comment]
> client.ConnectAsync(new Uri("ws://localhost:50002/ws/z")
1) You doing it right on client side.
> only the first one is accepted on the server side. 
2) Do you accept connection in loop? here is example https://github.com/deniszykov/WebSocketListener/blob/master/Samples/EchoServer/Program.cs
>  I don't see where I can specify a Uri when sending a message from client. For sending, I'm just doing this
3) WS protocol does not control or describe content of passed messages. WS message is binary blob, you can apply any formatting and structure to it.
You can check and switch by request URL only on initial WS connection because this URL is part of HTTP protocol. WS protocol is based on HTTP protocol and this URI is part of connection handshake.
> I have to call ConnectAsync() with a different URL and then dispose of that on a per call basis. 
4) Each WS is persistent connection from client to server. If should keep and reuse this connection untill you have no need in it. Then Dispose() it.

**Comment by gwalschl** [comment]
I see what you're saying and I now have my code working.  Thanks again for being so gracious with your time.  Much appreciated!

**Comment by deniszykov** [comment]
No problem 👍
